server:
    port: 8080
  
spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/bookdemo
        username: user
        password: pass
    jpa:
        hibernate:
            ddl-auto: validate
    liquibase:
        enabled: false
        change-log: classpath:liquibase/changelog.xml

    security:
        user:
            name: dominik
            password: pass
       
      


bookdemo:
    string-prop: string value
    numProp: 42
    nested:
        configParam: value42

logging:
    level:
        "[org.springframework.jdbc.core.JdbcTemplate]": DEBUG
        "[org.hibernate.SQL]": DEBUG
        #"[org.hibernate.type.descriptor.sql]": TRACE
        liquibase: WARN
        "[org.jooq]": debug
        
---

spring:
    profiles: prod

    liquibase:
        enabled: true


server:
    port: 8090